language: node_js
node_js:
  - 12

services:
  - docker

before_script:
  - touch .env
  - touch ./config/env.json
  - node ./scripts/testsSetup.js
  - docker build -t aquilacms/aquilacms .
  - docker pull mongo

script:
  - docker network create aquila
  - docker run --name mongo -p 27017:27017 --network=aquila mongo
  - docker exec -i mongo sh -c 'mongorestore --archive --drop' < ./test/data/test/archive
  - docker run --name aquilacms -p 127.0.0.1:3010:3010/tcp --network=aquila aquilacms/aquilacms
  - yarn test